name: Soup-FFA
version: '${project.version}'
main: hgpractice.soupffa.SoupFFA
author: "Tim Bahlinger (Creeper_craft)"
depend:
  - HGP-GameAPI
commands:
  stats:
    description: Displays the own players stats or the stats of a specified player.
  setloc:
    aliases:
      - setlocation
    description: Sets a location. Available locations are spawn, pos1 and pos2.
